CREATE TABLE [dbo].[Role] (
    [Id]    INT           IDENTITY (1, 1) NOT NULL,
    [Key]   NVARCHAR (50) NOT NULL,
    [Value] NVARCHAR (50) NOT NULL,
    CONSTRAINT [PK_Role] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [UQ_Name] UNIQUE NONCLUSTERED ([Key] ASC)
);

